insert into ingredients(id, name) values(1, 'Pomodoro');
insert into ingredients(id, name) values(2, 'Mozzarella');
insert into ingredients(id, name) values(3, 'Formaggio');
insert into ingredients(id, name) values(4, 'Wurstel');
insert into ingredients(id, name) values(5, 'Patatine fritte');
insert into ingredients(id, name) values(6, 'Prosciutto');
insert into ingredients(id, name) values(7, 'Rucola');
insert into ingredients(id, name) values(8, 'Grana');
insert into ingredients(id, name) values(9, 'Brie');
insert into ingredients(id, name) values(10, 'Zucchine');
insert into ingredients(id, name) values(11, 'Pomodoro a fette');
insert into ingredients(id, name) values(12, 'Peperoni');
insert into ingredients(id, name) values(13, 'Insalata');
insert into ingredients(id, name) values(14, 'Mais');
insert into ingredients(id, name) values(15, 'Origano');
insert into ingredients(id, name) values(16, 'Aglio');
insert into ingredients(id, name) values(17, 'Funghi');
