insert into pos.drinks(id, name, price) values(1, 'Birra piccola', 2);
insert into pos.drinks(id, name, price) values(2, 'Birra grande', 4);
insert into pos.drinks(id, name, price) values(3, 'Metro Birra piccola', 15);
insert into pos.drinks(id, name, price) values(4, 'Metro Birra grande', 30);
insert into pos.drinks(id, name, price) values(5, 'Spritz Macchiato piccolo', 2);
insert into pos.drinks(id, name, price) values(6, 'Spritz Macchiato grande', 4);
insert into pos.drinks(id, name, price) values(7, 'Spritz Liscio piccolo', 1.5);
insert into pos.drinks(id, name, price) values(8, 'Spritz Liscio grande', 3);
insert into pos.drinks(id, name, price) values(9, 'Metro Spritz Macchiato piccolo', 15);
insert into pos.drinks(id, name, price) values(10, 'Metro Spritz Macchiato grande', 30);
insert into pos.drinks(id, name, price) values(11, 'Metro Spritz Liscio piccolo', 11);
insert into pos.drinks(id, name, price) values(12, 'Metro Spritz Liscio grande', 22);
insert into pos.drinks(id, name, price) values(13, 'Coca Cola piccola', 2);
insert into pos.drinks(id, name, price) values(14, 'Coca Cola grande', 4);
insert into pos.drinks(id, name, price) values(15, 'Lattina', 2);
insert into pos.drinks(id, name, price) values(16, 'Acqua', 1);
insert into pos.drinks(id, name, price) values(17, 'Caffè', 1);