insert into dishes_ingredients values(13,18);
insert into dishes_ingredients values(13,19);
insert into dishes_ingredients values(14,18);
insert into dishes_ingredients values(14,19);
insert into dishes_ingredients values(14,22);
insert into dishes_ingredients values(15,18);
insert into dishes_ingredients values(15,19);
insert into dishes_ingredients values(15,23);
insert into dishes_ingredients values(15,34);
