insert into ingredients(name) values('Pomodoro');
insert into ingredients(name) values('Mozzarella');
insert into ingredients(name) values('Formaggio');
insert into ingredients(name) values('Wurstel');
insert into ingredients(name) values('Patatine fritte');
insert into ingredients(name) values('Prosciutto');
insert into ingredients(name) values('Rucola');
insert into ingredients(name) values('Grana');
insert into ingredients(name) values('Brie');
insert into ingredients(name) values('Zucchine');
insert into ingredients(name) values('Pomodoro a fette');
insert into ingredients(name) values('Peperoni');
insert into ingredients(name) values('Insalata');
insert into ingredients(name) values('Mais');
insert into ingredients(name) values('Origano');
insert into ingredients(name) values('Aglio');